### ISSUE TITLE
SBOM references

### ISSUE THREAD

**Issue by davaya** [oasis-tcs/openc2-ap-sbom#38]
A decision-maker wants to know "what SBOMs apply to device X".  That question may be answered by:
Q1) querying device X using OpenC2
Q2) querying a device manager (PACE PCS or commercial endpoint management product) using OpenC2
Q3) querying a datastore using OpenC2
Q4) querying a datastore using a datastore protocol

An OpenC2 response in cases 1-3 could be:
R1) An SBOM or set of SBOMs
R2) A set of SBOM webserver URLs
R3) A set of SBOM unique IDs that could be looked up and returned from a datastore

I'd like to eliminate Q3 immediately - the purpose of a datastore is to answer queries, and trying to replicate SQL or NoSQL APIs using OpenC2 would be completely wasted effort.

Next on the chopping block is Q1 - do we expect endpoint devices in the future to carry SBOMs for their software loads, or are approaches like MUD and endpoint management more realistic?  For the CAW I'd focus on Q4 first (define what retrieval looks like with a canned datastore), then Q2 for OpenC2 to populate the datastore with live data.

For the CAW OpenC2 response to Q2, I'd recommend references (R2, R3) rather than carrying SBOM data in the response.

Thoughts and comments?

**Comment by dlemire60** [comment]
I agree completely about eliminating Q3 as an option. I can't foresee a situation where it makes sense to wrap more or less generic database queries in OpenC2 .

I'm on the fence regarding Q1, leaning somewhat toward keeping it. My rationale:

 * SBOM is an immature technology and the definition of its "ecosystem" still seems to have a lot of churn, so I think it's premature to rule out supporting a potential use case
 * I anticipate some number of vendors will take the simple-minded approach of storing the SBOM on the device, particularly for low-end devices (e.g., some simple IoT devices)
 * Request/reply is the basic OpenC2 interaction model, and Q1/R1 is consistent with it.
 
I do agree with the proposed development priorities of

 1. Define the data store interface for storing and retrieving SBOMs
 2. Develop the Q2 / R3 interaction pattern for having an OpenC2 Producer shepherd the process of getting SBOMs into the data store, and informing the decision maker where to get the information.  Q2 / R2 is similar, but if we want the decision maker to operate with read-only access to the data store, it seems better to have the OpenC2 Producer churn through the URLs and populate the data store so the decision maker's interface is consistent regardless of where the SBOMs actually originated.

OTOH, I'd like to work priorities 1 and 2 in parallel as much as possible. We're only 12 weeks from the CAW, which will go by  quickly.

**Comment by sparrell** [comment]
I am fine and agree with Q3. Ie you don't use OpenC2 to do that.
I propose deleting Q4 - ie you don't use OpenC2 to do that. I'm not against doing it - just that it doesn't affect the OpenC2 SBOM AP (ie it's not an issue for this work product).
I object to removing Q1. Maybe others don't need it, but I have it already and think it's an important use case.
I recommend keeping Q1 & Q2.

I am fine with R1,2,3 conceptually, but I think of it slightly differently:
Q1: what SBOMs do you have?
R1: list of SBOM identifiers, metatdata about them (eg SPDX/CDX, what each is SBOM of, ...), and where to find them (on device, uri, somewhere else)
Q2: give me SBOM with sufficient info to know which one (eg id=uuidx, type=CDX, whatever)
R2: the single SBOM requested in the format requested

Note if a URI is returned in R1, or if somewhere else than on device, then it's Q/R is outside scope of SBOM-AP.

Note I didn't include JSON/XML/CBOR/... as serializations because in a different issue I'd like to kick that can down the road and only allow JSON right now. However we can still include serialization=JSON in the Q2/R2 - just for now don't allow any other choices.

My focus will be on the above Q1,2,R1,2 from the device

**Comment by dlemire60** [comment]
I think it makes sense to support the introspection-oriented scenario Duncan described. It get a little confusing insofar as Duncan's post uses Q2 in two different ways, the second of which is different from DaveK's Q2. 

I think we've got a couple of things to resolve, overall:

1. What SBOM-retrieval use cases do we envisions (more or less globally)?
2. Which SBOM-retrieval use cases involve OpenC2?
3. Which of the the SBOM-retrieval use cases involving OpenC2 are part of the SBOM AP, vs. some other AP?

Duncan has planted a stake (I presume for the June '23 CASP plugfest:

1. Direct SBOM retrieval from the device
2. This use case involves OpenC2
3. This use case is part of the SBOM AP.

That seems a rationale set of priorities for the moment. The broader set of questions should be taken up in our working meetings.

**Comment by sparrell** [comment]
close per 24-May-2023 working mtg discussion
